{
    "name": "Laboratory Management",
    "summary": "SENAITE-style laboratory workflow",
    "description": """
Laboratory management workflow implemented on Odoo:

- Analysis service catalog and profiles
- Sample accessioning and lifecycle
- Analysis execution and worksheet batching
- Result verification and report release
- More portal functions. Enjoy....
""",
    "version": "19.0.2.0.0",
    "category": "Healthcare",
    "author": "mamingxing",
    "website": "https://imytest.local",
    "license": "LGPL-3",
    "depends": ["base", "mail", "portal", "website", "account", "product", "base_setup", "sale", "website_sale"],
    "assets": {
        "web.assets_backend": [
            "laboratory_management/static/src/scss/chatter_sidebar.scss",
        ],
        "web.assets_frontend": [
            "laboratory_management/static/src/scss/portal_cards.scss",
        ],
    },
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/lab_sequence.xml",
        "data/lab_storage_sequence.xml",
        "data/lab_test_request_sequence.xml",
        "data/lab_request_billing_sequence.xml",
        "data/report_dispatch_sequence.xml",
        "data/lab_quality_sequence.xml",
        "data/lab_custody_batch_sequence.xml",
        "data/lab_custody_closure_sequence.xml",
        "data/ir_cron.xml",
        "data/report_template_data.xml",
        "data/review_reason_template_data.xml",
        "data/custody_exception_template_data.xml",
        "data/lab_custody_sla_policy_data.xml",
        "data/manual_review_digest_config_data.xml",
        "data/lab_ecommerce_config_data.xml",
        "data/lab_sop_data.xml",
        "data/lab_permission_matrix_data.xml",
        "data/lab_interface_mapping_data.xml",
        "data/lab_operational_clone_data.xml",
        "data/lab_sop_execution_data.xml",
        "data/lab_operational_workflow_data.xml",
        "data/lab_governance_extension_data.xml",
        "report/lab_report_templates.xml",
        "report/lab_report_actions.xml",
        "report/lab_custody_report_templates.xml",
        "report/lab_custody_report_actions.xml",
        "views/laboratory_management_menus.xml",
        "views/lab_service_views.xml",
        "views/lab_notification_views.xml",
        "views/lab_review_views.xml",
        "views/lab_profile_views.xml",
        "views/lab_report_template_views.xml",
        "views/lab_test_request_views.xml",
        "views/lab_request_billing_views.xml",
        "views/lab_ecommerce_views.xml",
        "views/lab_sample_review_views.xml",
        "views/lab_sample_ai_views.xml",
        "views/lab_report_dispatch_views.xml",
        "views/lab_quality_program_views.xml",
        "views/lab_quality_extended_views.xml",
        "views/lab_capa_views.xml",
        "views/lab_sop_views.xml",
        "views/lab_sop_execution_views.xml",
        "views/lab_sop_profile_matrix_views.xml",
        "views/lab_sop_advanced_governance_views.xml",
        "views/lab_reagent_views.xml",
        "views/lab_instrument_views.xml",
        "views/lab_interface_mapping_views.xml",
        "views/lab_interface_views.xml",
        "views/lab_interface_audit_views.xml",
        "views/lab_operational_clone_views.xml",
        "views/lab_operational_workflow_views.xml",
        "views/lab_governance_extension_views.xml",
        "views/lab_governance_plus_views.xml",
        "views/lab_workstation_governance_views.xml",
        "views/lab_import_job_views.xml",
        "views/lab_storage_views.xml",
        "wizard/lab_custody_batch_add_samples_wizard_views.xml",
        "views/lab_custody_batch_views.xml",
        "views/lab_custody_closure_views.xml",
        "views/lab_custody_governance_views.xml",
        "views/lab_sample_views.xml",
        "views/lab_analysis_views.xml",
        "views/lab_worksheet_views.xml",
        "views/lab_qc_views.xml",
        "wizard/lab_kpi_dashboard_wizard_views.xml",
        "wizard/lab_workbench_wizard_views.xml",
        "wizard/lab_sample_receive_wizard_views.xml",
        "wizard/lab_sample_transfer_custody_wizard_views.xml",
        "wizard/lab_analysis_bulk_review_wizard_views.xml",
        "wizard/lab_manual_review_report_wizard_views.xml",
        "wizard/lab_storage_bulk_operation_wizard_views.xml",
        "wizard/lab_custody_investigation_bulk_update_wizard_views.xml",
        "wizard/lab_result_import_wizard_views.xml",
        "wizard/lab_instrument_result_import_wizard_views.xml",
        "views/portal_templates.xml",
    ],
    "installable": True,
    "application": True,
}
